const LOGIN = 'LOGIN'
const LOGOUT = 'LOGOUT'
const LOGIN_FAILED = 'LOGIN_FAILED'

const ADD_PROJECT = 'ADD_PROJECT'
const DELETE_PROJECT = 'DELETE_PROJECT'
const EDIT_PROJECT = 'EDIT_PROJECT'
const SET_PROJECTS = 'SET_PROJECTS'
const REMOVE_PROJECTS_ON_LOGOUT = 'REMOVE_PROJECTS_ON_LOGOUT'

const ADD_TASK = 'ADD_TASK'
const REMOVE_TASK = 'REMOVE_TASK'
const EDIT_TASK = 'EDIT_TASK'
const SET_TASKS = 'SET_TASKS'
const REMOVE_TASKS_ON_LOGOUT = 'REMOVE_TASKS_ON_LOGOUT'

export {
  LOGIN,
  LOGOUT,
  ADD_PROJECT,
  DELETE_PROJECT,
  EDIT_PROJECT,
  ADD_TASK,
  REMOVE_TASK,
  EDIT_TASK,
  SET_PROJECTS,
  LOGIN_FAILED,
  SET_TASKS,
  REMOVE_PROJECTS_ON_LOGOUT,
  REMOVE_TASKS_ON_LOGOUT
}
