const LOGIN = 'LOGIN'
const LOGOUT = 'LOGOUT'
const LOGIN_FAILED = 'LOGIN_FAILED'

const ADD_PROJECT = 'ADD_PROJECT'
const REMOVE_PROJECT = 'REMOVE_PROJECT'
const EDIT_PROJECT = 'EDIT_PROJECT'
const SET_PROJECTS = 'SET_PROJECTS'

const ADD_TASK = 'ADD_TASK'
const REMOVE_TASK = 'REMOVE_TASK'
const EDIT_TASK = 'EDIT_TASK'

export {
  LOGIN,
  LOGOUT,
  ADD_PROJECT,
  REMOVE_PROJECT,
  EDIT_PROJECT,
  ADD_TASK,
  REMOVE_TASK,
  EDIT_TASK,
  SET_PROJECTS,
  LOGIN_FAILED
}
